config/routes.rb
Autopedia::Application.routes.draw do

  resources :banners

  devise_for :users, :path => 'users', :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  root :to => 'pages#inicio'

  get "controls/" => 'controls#index'

  match '/pages/inicio' => 'pages#inicio', :as => 'inicio', :via => :get
  match '/pages/inicio' => 'pages#inicio_send', :as => 'inicio', :via => :post

  get "/pages/inicio" => 'pages#inicio', :as => :page, :format => false
 
  match "/pages/autos_en_venta" => 'pages#autos_en_venta', :as => 'autos_en_venta', :via => :get
  match "/pages/autos_en_venta" => 'pages#autos_en_venta_send', :as => 'autos_en_venta', :via => :post

  match "/pages/autos_en_venta/:id" => 'pages#auto', :as => :page, :via => :get
  match "/pages/autos_en_venta/:id" => 'pages#auto_send', :as => :page, :via => :post
 
  get "/pages/directorio" => 'pages#directorio', :as => :page, :format => false
  get "/pages/directorio/:id" => 'pages#negocio', :as => :page, :format => false
 
  get "/pages/revista" => 'pages#revista', :as => :page, :format => false
 
  get "/pages/tv" => 'pages#tv', :as => :page, :format => false
  get "/pages/episodio/:id" => 'pages#episodio', :as => :page, :format => false
 
  match '/pages/certificate' => 'pages#certificate', :as => 'certificate', :via => :get
  match '/pages/certificate' => 'pages#certification_send', :as => 'certificate', :via => :post
 
  match '/pages/contacto' => 'pages#contacto', :as => 'contacto', :via => :get
  match '/pages/contacto' => 'pages#create', :as => 'contacto', :via => :post
 
  get "/pages/ubicacion" => 'pages#ubicacion', :as => :page, :format => false
  get "/pages/poliza_de_legalidad" => 'pages#poliza_de_legalidad', :as => :page, :format => false
  get "/pages/acerca_de_nosotros" => 'pages#acerca_de_nosotros', :as => :page, :format => false
  get "/pages/publicidad" => 'pages#publicidad', :as => :page, :format => false

  resources :videos
  resources :magazines
  resources :companies
  resources :categories
  resources :cars
  resources :cities
  resources :states
  resources :countries
  resources :models
  resources :brands

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :video

  validates_presence_of :title, :video, :description
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  before_filter :authenticate_user!
 
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, :notice => 'Video was successfully created.' }
        format.json { render :json => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.json { render :json => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, :notice => 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation" class="alert alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= pluralize(@video.errors.count, "error") %> no permite que este Episodio de TV sea creado:</h4>
      <br />
      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Titulo' %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Video (520x320)' %>
    <%= f.text_area :video, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label 'Descripción' %>
    <%= f.text_area :description, :rows => 9 %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class="page-header">
  <h2>Editar Episodio de TV</h2>
</div> 

<%= render 'form' %>

<div class="form-actions">
  <%= link_to 'Mostrar', @video, :class => "btn" %>
  <%= link_to 'Regresar', videos_path, :class => "btn" %>
</div>

app/views/videos/index.html.erb
<div class="page-header">
  <h2>Lista de Episodios de TV</h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripción</th>
      <th>Video</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>    
  <tbody>
    <% if @videos.empty? %>
    <tr>
      <td colspan="6">Aun sin Episodios de TV.</td>
    </tr>
    <% else %>
      <% @videos.each do |video| %>
      <tr>
      	<td><%= video.title %></td>
    		<td><%= video.description %></td> 
    		<td><%= video.video.html_safe %></td>   
    		<td><%= link_to 'Mostrar', video %></td>
    		<td><%= link_to 'Editar', edit_video_path(video) %></td>
     		<td><%= link_to 'Eliminar', video, :method => :delete, :data => { :confirm => '¿Estas seguro?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nuevo Episodio de TV', new_video_path, :class => "btn btn-primary" %>

 

app/views/videos/new.html.erb
<div class="page-header">
  <h2>Nuevo Episodio de TV</h2>
</div> 

<%= render 'form' %>

<div class="form-actions">
  <%= link_to 'Regresar', videos_path, :class => "btn" %>
</div>

app/views/videos/show.html.erb
<div class="page-header">
  <h2><%= @video.title %></h2>
</div>   
<p>
	<b>Fecha de Publicación:</b>
	<%= l @video.created_at, :formats => :long %>
<p>
	<b>Descripción:</b>
	<%= @video.description %>
</p>

<%= @video.video.html_safe %>

<div class="form-actions">
  <%= link_to 'Editar', edit_video_path(@video), :class => "btn" %>
  <%= link_to 'Regresar', videos_path, :class => "btn" %>
</div>