config/routes.rb
Autopedia::Application.routes.draw do

  resources :banners

  devise_for :users, :path => 'users', :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  root :to => 'pages#inicio'

  get "controls/" => 'controls#index'

  match '/pages/inicio' => 'pages#inicio', :as => 'inicio', :via => :get
  match '/pages/inicio' => 'pages#inicio_send', :as => 'inicio', :via => :post

  get "/pages/inicio" => 'pages#inicio', :as => :page, :format => false
 
  match "/pages/autos_en_venta" => 'pages#autos_en_venta', :as => 'autos_en_venta', :via => :get
  match "/pages/autos_en_venta" => 'pages#autos_en_venta_send', :as => 'autos_en_venta', :via => :post

  match "/pages/autos_en_venta/:id" => 'pages#auto', :as => :page, :via => :get
  match "/pages/autos_en_venta/:id" => 'pages#auto_send', :as => :page, :via => :post
 
  get "/pages/directorio" => 'pages#directorio', :as => :page, :format => false
  get "/pages/directorio/:id" => 'pages#negocio', :as => :page, :format => false
 
  get "/pages/revista" => 'pages#revista', :as => :page, :format => false
 
  get "/pages/tv" => 'pages#tv', :as => :page, :format => false
  get "/pages/episodio/:id" => 'pages#episodio', :as => :page, :format => false
 
  match '/pages/certificate' => 'pages#certificate', :as => 'certificate', :via => :get
  match '/pages/certificate' => 'pages#certification_send', :as => 'certificate', :via => :post
 
  match '/pages/contacto' => 'pages#contacto', :as => 'contacto', :via => :get
  match '/pages/contacto' => 'pages#create', :as => 'contacto', :via => :post
 
  get "/pages/ubicacion" => 'pages#ubicacion', :as => :page, :format => false
  get "/pages/poliza_de_legalidad" => 'pages#poliza_de_legalidad', :as => :page, :format => false
  get "/pages/acerca_de_nosotros" => 'pages#acerca_de_nosotros', :as => :page, :format => false
  get "/pages/publicidad" => 'pages#publicidad', :as => :page, :format => false

  resources :videos
  resources :magazines
  resources :companies
  resources :categories
  resources :cars
  resources :cities
  resources :states
  resources :countries
  resources :models
  resources :brands

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :models
  has_many :cars
  attr_accessible :description, :title, :logo, :delete_logo
  
  #delete existing logo from edit view with checkbox.
  attr_accessor :delete_logo
  before_validation { logo.clear if delete_logo == '1' }
  
  #validate
  validates_presence_of :title

  #paperclip
  has_attached_file :logo, :styles => { :thumb => "100x100#", :small => "100x65#" }

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  before_filter :authenticate_user!
  
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, :notice => 'Brand was successfully created.' }
        format.json { render :json => @brand, :status => :created, :location => @brand }
      else
        format.html { render :action => "new" }
        format.json { render :json => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        if params[:brand][:delete_logo]
          @brand.logo = nil
          @brand.save
        end
        format.html { redirect_to @brand, :notice => 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand, :html => { :multipart => true, :id => "fileupload" }) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation" class="alert alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= pluralize(@brand.errors.count, "error") %> no permite que esta Marca sea creada:</h4>
      <br />
      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Titulo' %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Descripción' %>
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <% if @brand.logo? %>
      <%= link_to image_tag(f.object.logo.url(:thumb)), f.object.logo.url(:original) %>
      <%= f.check_box(:delete_logo) %>
    <% else %>
      <span class="btn btn-success fileinput-button">
      <em class="icon-picture icon-white"></em>
      <span>Adjuntar imagen...</span>
        <%= f.file_field :logo %>
      </span>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<div class="page-header">
  <h2>Editar Marca</h2>
</div>

<%= render 'form' %>

<div class="form-actions">
  <%= link_to 'Mostrar', @brand, :class => "btn" %> <%= link_to 'Regresar', brands_path, :class => "btn" %>
</div>

app/views/brands/index.html.erb
<div class="page-header">
  <h2>Lista de Marcas</h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripción</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% if @brands.empty? %>
    <tr>
      <td colspan="5">Aun sin Marcas.</td>
    </tr>
    <% else %>
      <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.title %></td>
        <td><%= brand.description %></td>
        <td><%= link_to 'Mostrar', brand %></td>
        <td><%= link_to 'Editar', edit_brand_path(brand) %></td>
        <td><%= link_to 'Eliminar', brand, :method => :delete, :data => { :confirm => '¿Estas seguro?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
  
</table>

<%= link_to 'Nueva Marca', new_brand_path, :class => "btn btn-primary" %>

app/views/brands/new.html.erb
<div class="page-header">
  <h2>Nueva Marca</h2>
</div>

<%= render 'form' %>

<div class="form-actions">
  <%= link_to 'Regresar', brands_path, :class => 'btn' %>
</div>

app/views/brands/show.html.erb
<div class="page-header">
  <h2><%= @brand.title %></h2>
</div>

<p>
  <b>Descripción:</b>
  <%= @brand.description %>
</p>

<p>
	<b>Logo:</b>
	<% if @brand.logo? %>
	<%= image_tag @brand.logo.url(:thumb) %>
	<%= image_tag @brand.logo.url(:small) %>
	<% else %>
		No hay imagen adjunta.
	<% end %>
</p>

<div class="form-actions">
  <%= link_to 'Editar', edit_brand_path(@brand), :class => "btn" %> <%= link_to 'Regresar', brands_path, :class => "btn" %>
</div> 